[build]
  command = "yarn build"
  publish = "dist/"
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "16"
  PYTHON_VERSION = "3.10"

[dev]
  command = "yarn start"
  port = 3000
  publish = "dist/"

[[plugins]]
  package = "netlify-plugin-inline-functions-env-typescript"
